import rtconfig

from building import *
import os

cwd = GetCurrentDir()
group = []

# 自动发现含 SConscript 的组件子目录
list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
